export const links = {
  HOME: "/",
  ABOUT: "/about",
  BLOG: "/blog",
  EVENTS: "/events",
  INTERNATIONAL: "/international",
  CONTACT: "/contact",
  LOGIN: "/login",
  REGISTER: "/register",
  NEWS: "/news",
  TERMS: "/terms",
  COOKIE_POLICY: "/cookie",
  PRIVACY: "/privacy",
  WEATHER: "/weather",
};
